### ISSUE TITLE
trained  weights 

### ISSUE THREAD

**Issue by cuevas1208** [andrewlstewart/FlowNet_v1_TF2#3]
do you have the trained weights?

**Comment by andrewlstewart** [comment]
Hi there, I didn't have the compute to try and thoroughly train these models myself.  Try checking out the [original authors](https://github.com/lmb-freiburg/netdef-docker) or you may be able to download the checkpoints for their TF1.4 models [here](https://github.com/lmb-freiburg/netdef_models/blob/master/FlowNet3/download_snapshots.sh) and try and port them to TF2.  If I find time I may take another look at this and see if I can implement the FlowNet3 architecture in TF2 and pull their weights.  Good luck!

**Comment by cuevas1208** [comment]
Thanks 👍

**Comment by Somayehkiany** [comment]
Hi, please explain how you implement this fingerprint - recognition program?
